name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.37+mc26.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef2d7b5976c358f36677bbfb3e9cb0300d5ad1bec1b0f3a91b9acaf0a592fcef"

[versions]
minecraft = "26.3"
neoforge = "26.3.0.23-beta"
