name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc26.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0da3e533e5aa2106de904cc5a465c473733d8168303e82baaeaa9217221541f4"

[versions]
minecraft = "26.3"
neoforge = "26.3.0.10-beta"
