name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942f3c95a49bb4c1c45b45c8c5eb4af902abe5793f61a5b7ad692719050e33e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
