name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a938f081f5a3bd0f669b7d3ccf74a2e181739f902c9ef17f74d2e2c3742f3e5e"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
