name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.13+mc26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "220ae11a227803cdc8e51324f052193e9adda5fcd101a81598634d0514602ed5"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.79"
