name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.13+mc26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cabc791cc1694a89ba86e827da4336b0b8b664639dc39989ca98dc62b302be6"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.79"
