name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "229f974a9953ab987c58339f1b18df352fcb9332743fe81a4c928d6bd5d5c44d"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
