name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "370c4afbb852a3b1bbdcd9a41130edfb010a9a11f38da70169f8f8df1e30920f"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
