name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.117+mc20.1.fabric.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68fe9efe5c51f3fa7e6db69fa84522b50be43ae750968d46442e64fef64e812b"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
