name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72d48453f30b33359230a42af5b89dd490b5de42b818b57b0f49ea4249ea1784"

[versions]
fabric = "0.19.5"
minecraft = "1.21.5"
