name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3980a7bb30d1c50c1c9f92511b79d9dfbde51746d467e7d8a40b4c267356e204"

[versions]
fabric = "0.19.5"
minecraft = "1.21.5"
