name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6168aa1d8c5e8feae523e37db68347d8f96b2b319d0e7b6ea1bdceec1e34660"

[versions]
fabric = "0.19.5"
minecraft = "1.21.5"
