name = "Complexly Optimized"
author = "Ratchet"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46ae6d46b2c1fc828e49ed685fcafa164bef0c5055dca79376dd47cc89f4814c"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
