name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-conservative"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c31e1355b3387af761d58e17b5e0e382a205e8385e88c7fc45ebb1cbfe63ffe"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
