name = "Complexly Optimized"
author = "Ratchet"
version = "21.5.1+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0c80001a016f343c40ccf27a95123981dc6b4e1b1f35daeded60162a5458016"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
