name = "Complexly Optimized"
author = "Ratchet"
version = ""
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84484f3612505848b8b78b7d8281905660b258589b21f0222e1a210d4a04f924"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
