name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-neo+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4ba9b374a6ba548bcc45a0bf3465f6418357e9af6c551fe3145f80b29002c46"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
