name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36-SNAPSHOT+mc1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d910fefe7f4a52031e2edc3952906c360b99afdb55f3e26637caa135f278500"

[versions]
fabric = "0.19.5"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.5"]
