name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0404b6137fd6c7b031d2e07a284c6f76d2904b262049415c1a159034dbd34dc"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
