name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52dbd7786aa6b01a5dc4f57ada3d10321aa88462d42eab9d5fcd8d35177a61e8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
