name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82cef3e6db2e11d95b8443d254598c8a7f11e4efde59b78762139ece048564ce"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
