name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.117+mc20.1.forge.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da5b58fa7d0c5c272c9ed5167d35ea9ffddfe7c5a8c4cbf738cb2f626eaa4f84"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
