name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e173db557b8c51a824785f2e1ed0fa428926bbab3328eebc9a852164a3e08f9"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
