name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24b1d9321f1886941b5fd38bae91d3cc1a3775ef9eeefd035f35bc961ca81933"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
