name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba930080fd4cbe8bd544998645975fecbefb716349f6bb60fd7a666b9d1a51f8"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
