name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3aee085de0716dd090ca601175e535c2ab047e1480d31fe779c6c2b3d9f7c8"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
