name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19b838f6c7155143ecea7bfaef4d00a151bd205ee6bcb91b0606fa9c9cdc21ee"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
