name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c75db7e44294520966cdaf00897a2b33d1c0b2026a4f538adf229238a8afe98"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
