name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a476f03050cbac8cb8143b61023734c5022502c77009a3dba05ee72a54c38730"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
