name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "329f8cd5b9a759f889fac40467dba5aaa17f025d2d341799e2f3046775fec607"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
