name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54dc77d0c66f74fc19fc169a70eda9a85e3a35b6b280eabd565c6f172e32c53f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
