name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "120ff78b170e1830572d9be3089cd7e67f9fc6da37c9fc063e2404d6633017d4"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
