name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.18+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d83eb84063a93de11bf009897bde4b2e66a2baf446cc8efd77335650e1d4b6e"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
