name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1dc456f41598928cdd9bce2886f8c7a2c070c522bdee9bcda3b3ba0ca314db"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
