name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.30-SNAPSHOT+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074910320a53166f014c2974e7ac3322b7fcb6d703dc8230a893b8df769c9fe2"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
