name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-vanilla"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04c4c0f5c0da8ef46f32158e19db3b6dd1d81352e5e5ded1e7a2e1003bfc20e6"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
