name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.8-SNAPSHOT+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb93844994ba6855d7981a528480d7df327958e4b994f5bf925c6e8a825e0e9"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
