name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a7b0316e6b319ccc6c03ae2c5dabc49818a4cbb8436feeb5b441198a4cdd24c"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
