name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.8-SNAPSHOT+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf1f0aed95867a26090ccd314bac46fc0e622a2bb1805d60bfc65c49591e5ae6"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
