name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-forge-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e655cfc492cc31c3e03016c46117703bb8d0f04a0dd835b7fc5831461dbbc59"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
