name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471d9780203af446df7b8274f33c24a795985e0328171042029e088a67ecf41b"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
