name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.117+mc26.1.fabric.vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f7bb153fc7f97a20fcafc72073896ed8e3f2ec661efe938f2b1767422821fc"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
