name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-forge-stable"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "305d3613b3a924741d1c52e45a77e28e87f96fe73b213b2d90e4118528c747c3"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
