name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-forge-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b7e6e5b0a9f4754586a12535a4c5ff3b21a31ba2bae7b8dfa2f31330320fdef"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
