name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.8+mc1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00d91725fd2223d1a98a7068822a901a4ea9edbe4a59cfc9d3fb43141073522f"

[versions]
fabric = "0.19.5"
minecraft = "1.21.5"
