name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14e0177d5088f0862d98f7c45434b863db0db0a4e631480da003a12e43cd5a8a"

[versions]
fabric = "0.19.5"
minecraft = "1.21.5"
