name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-vanilla"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d54b1937dd9e76c1b58dda469daecefeeda9692937fd2c0a103ff1259840841"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
