name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac013c36edf02e5822e670449a58a69ff6fb40505cb6a080a811273c53f2914"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
