name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b8884b651c800a805a1de68a2322b59a22823466acff3c6e7a6459f95611086"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
