name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.2-anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df3aac8ef047d1076540742db4555a5854aa0ec2fb59ab94e0699a5046137ed"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
