name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.142-dev+mc21.1.neoforge.lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea91a7a0ffd3c394950babc61b2a179c9e18e3eb992d1947c0ddd626e666ef37"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
