name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.126+mc26.2.fab.law"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b70f71e3d895078421e99685148504ce8bf2c6394c7c41e2ac11a9a0be901386"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
