name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2c46dad699ffd7cd85c17174297f2729d8f6e6a82c19c3c0224744e72f36e23"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
