name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.15+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75804b2a360893976e71f101f124e2b00e92797c8cefc60a1a7858365b5904fc"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
