name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f2c78b3c14f7e28a5f691c2a4fe8d0f94bef7a372d8e68789becd26ba71f71a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
