name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3836e77b3a884b274afd887225ecf1591835bba1c87c9fec2d9df8e558cc1cd"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
