name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b97a14d000d6825520c3f43866b8d75e5c71f1a4b5fb217b88cae2c35199e97"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
