name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.23+mc1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ef37fcb6b4459bc68edf35f8e243f5fbcc88522a1cf53569de953f04add24e3"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
