name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddff6af2094b551922ec9903069a8ef9985c1cbceee94e19287f46af7866bfb5"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
