name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge-aggressive"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb8319f61114858c9ecb1e9a2064f533cd1cbf969ba6d0eb3469ef1992f16927"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
