name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf052bedf11a246081227d45ac8cccb71d59859d5b86d73c9c5dae568d74e48e"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
