name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a95a28592bef94bfa739b52e9275d99354d246e76aceac55c70d0344da5702d8"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
