name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-fabric-stable"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52d5a6610368b71108d8ab9d30cf372808433b30d0f589ea3d1099cf442d4921"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
