name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.122+mc21.5.fabric.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96378723663a4d5111eba5dec0b92c1b71e7f6e9d99120861fa6dec79ea89b72"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
