name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31+mc26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb84faf307aee6721355f1435fb315880f7ea22d7e4d44dd4f3ec851fc824188"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
