name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.32-SNAPSHOT+mc26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d06c74a6f0f7129e2e2116caaaaa8b5e2d342ca001ac34b30cd1f4efdabd424b"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
