name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.4+mc21.1.neo.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6b2edec4a65c686497dce6b43e063012967d7fbb78cf3ac66b6605caca03cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
