name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.8+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "228db51dffc36f0047cdf02f0269d006c192620f51c0f290f205cc19a596d6d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
