name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.9+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59420da4e83ab154710ac748b142915bdad2baa7a8a1f2619be7d95ce05f6768"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
