name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-neo+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "547a6df704aaea51edf7673855801fec24e9ba4f86ff54da256375e2d777c489"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
