name = "Complexly Optimized"
author = "Ratchet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5074be41a18db8503b4fceb41055e7616abf3c41ad2a86ef72e159f7487edb7"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
