name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.4+mc26.1.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10ff8ec8b29ad9dcbe5b0d3faf0e5223a5134808798cf12cf0ee9ce76499f964"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
