name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.6+mc26.1.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6829b2f020c5b54735bf2bb7db12484605fad2317b0cf425a4d2356a66ce032"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
