hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "configureddefaults/config/crash_assistant/config.toml"

[[files]]
file = "configureddefaults/config/dynamic_fps.json"

[[files]]
file = "configureddefaults/config/ferritecore.mixin.properties"

[[files]]
file = "configureddefaults/config/kerria.json"

[[files]]
file = "configureddefaults/config/modernfix-mixins.properties"

[[files]]
file = "configureddefaults/config/modmenu.json"

[[files]]
file = "configureddefaults/config/moreculling.toml"

[[files]]
file = "configureddefaults/config/quick-pack.json"

[[files]]
file = "configureddefaults/config/sodium-options.json"

[[files]]
file = "configureddefaults/options.txt"

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/jasione.pw.toml"
metafile = true

[[files]]
file = "mods/kerria-opt.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
metafile = true
