name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74fdd9df9d9909fb078ae74751e4bdba2608dc30b7b84f5fa8942e84fe063c8b"

[versions]
minecraft = "1.19.2"
quilt = "0.31.0-beta.4"
