name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.18+mc1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "473f429a0854c180fa13b40d93332c05d9e6a89be12d1dbedee55515a727174b"

[versions]
minecraft = "1.19.2"
quilt = "0.30.1"
