name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.18+mc1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "919209ac0999dd1223d1200bbb381a039275e60965b9bd74ee9388996e73b468"

[versions]
minecraft = "1.19.2"
quilt = "0.30.1"
