name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b3956133ab194550a8e1fad7f25dccf2b127bdc988d21f0b341a015f54a767e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
