name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b1bde99a3edfb35ddeb223927bb9e9f58ae40cb0ca75d5e32aaa8c5dc9c2eb1"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
