name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "426b97bbb5fe59845cf87d74621494b112bc528b729b73fa4fc295ae1f4cc8d5"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
