name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.8-SNAPSHOT+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ff77eda3bb844325d13bb6e48cc87b9d94b3367ead0ab4c25530df71c3ced3"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
