name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38acd4db420aae74db3486d11add88f83e17c1cafdbaecc1cb3eef72db292a04"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
