name = "Complexly Optimized"
author = "Ratchet"
version = "12.2.1-normal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1200f5d752d94000e7deae778f165a017722c07d5dea94a22440c12da526060"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
