name = "Complexly Optimized"
author = "Ratchet"
version = ""
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fbec0c5089801ba1325e950be731fd37739448b3dbe71049b7ce7f6fe0882ab"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
