name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.0+mc12.2.frg.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e64b733ef3bd86cf7a5619c4f888badccec4d708d0df1818fa8ba65c2b7b969"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
