name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.0+mc12.2.forge.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5266bb2484bfb938faf13a15b5d8641a03ba41b8f7954318fa761d29b2e703d0"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
