name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a8a672f3e538d856b0b218e4ab4371160ac454912fc8e8ba82bfdd0eb57d688"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
