name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ebfeb7a5710d882aa19e9a5360a403bb5c2994b8e3b81311b9a1d7b64305daa"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
