name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9334ba25f80632ee926a962facad4cb07b77ad5bda89cf88a7dd667cfe0218"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
