name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.122+mc20.1.fabric.lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b47160108463a1d4e1ce9040785839d41146ebc265ecb68ce3278d1f94d425f6"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
