name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.18+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c072b9da19cecd91d8ef67d05a52702a3c295204474d881dd42f92950001c90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
