name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.32-SNAPSHOT+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d549e7e5d1bb03172934b6930df01f29058c92b95ac8aaaa7e5dbd126569a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
