name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.23+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183c3060b34489b1b8df03ea5285e73cea74930abd0dd5c4f43efb361a5c8e94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
