name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c32aecc2f519cc69d783cfa12f1e7aa00f118276b335e4e5b4f0d41b2f3acb7"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
