name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-neo+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27523d192afdd651b7461696cbd64d63f2b3cb253dfbe5246add6b6654356438"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
