name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc1.12.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccabd24cd3dee4470cdc7d1093c81a097d5d898a2852a5ca1e38294b6b9a36e6"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
