name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric-vanilla"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70cbdcdd04291be65ab4962a653f66d4151ae5bac2097f83393f520f1a10e36a"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
