name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe85e5b92542abe05080c0a48242c1be545e29dfc91419ab51ad7540513cc162"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
