name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-normal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c9038b316840bc549f760cc278575627d4499816a4949b97ce5a0a20dea3b17"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
