name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-neo+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ecb4450b5b93cd40a466c5754997fca38b26656bcdf15e9e4b3c8832758041b"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
