name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-neo+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54d5437a2c7284839f8e2f224dc74926e5da478c15be4075a3d20c14da929466"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
