name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-neo+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "395ba532be195d17dd18283c6c0d354a9e15f45a4505c1db77d114222d21aa05"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
