name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.38+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d336942f17f83e4ab22d9a306f28a919e1adeaecd7eaba20f76234c03fef4359"

[versions]
fabric = "0.19.5"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.3"]
