name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36-SNAPSHOT+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80bab676160517e32174be86f62c037693a8c47395cce6f23557cb3a01c6fce6"

[versions]
fabric = "0.19.5"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.3"]
