name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.0+mc21.11.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c73f8d10a9ba32e056a9848801a8ec899482692fd482742bbba31b4ed5f724"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
