name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.9+mc21.11.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "224dc90170201245a013b515a57c77307af8c5b9876ed9b55e941c12a4666bc8"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
