name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b72758962baf1d21c6696edaaac1962edf722550fbebedb4a84f45b011e65f7"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
