name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630c5a072e6dc2156a617df7928ae2937c9cc0c8c87cc7887d89caaaf497aabc"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
