name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48f741c7293c457d0b716f0a70c6e82835f4bf8b7240d06e559b1f8b76b9f92b"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
