name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.9+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72a889f674c5cd4e1a5b3bb264111819af891f07e9c89366595cbb8633e457ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
