name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "529f8f471dae591ec87a7408a397e079702b316c09d2b3991889a88d0a829f20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
