name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.6+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3742b81ae62ecf0b44805d41933b99715db6065b1f3d354c494d5629924023b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
