name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-forge-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5182ab552bcdfa3a2b4e29c757dfe97c3f969e80a807cf56fe3d9c26ac8b3b73"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
