name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-forge-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3daa6c16babe194362e2a2ba377f4749e9da47d457585ef62dda17f044238c4b"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
