name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b598ddf172a278e299cf3f7f37455c1f5f29fa723e6eb56a82fc290fec167d"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
