name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-forge-vanilla"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6405638e14205ca1312a0363455b5f25b0c645fcca640610f6e7dce5981110fa"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
