hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"

[[files]]
file = "config/yosbr/config/modmenu.json"

[[files]]
file = "config/yosbr/config/quick-pack.json"

[[files]]
file = "config/yosbr/config/sodium-options.json"

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/hydrogen.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true
