name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.30+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6167e8cdaa30e60d3f18e0d507f0c8222bce1b29c33c4f963c81f2e1621cd55d"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
