name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cb3a4a6d193bfeb3bae6fe6f5064d2d1701967fa3409177638b37a111c5579d"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
