name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "448ca0575619e19c2410d09d2220be394d47f179c64bc589868e979a3dc0fdf0"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
