name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38a02bf75b42d68c88a4370b69b98a535b42cd1caf4c815a0768021ef619d473"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
