name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.13+mc26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2ae3bce3ffb7242e96c8a6ae13a62ebc5bd18ff8924db64b89031a220be4678"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.105"
