name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.6+mc26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e6f74bf47657ea366d462f94cd9129bef07de364e90c4a0a3d32007c9d0c2d"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.100"
