name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.117+mc18.2.forge.lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49cfce5a1c84e4fbafe971b632f2c70e7920c25a19abd1c7d1fd08b9258afd1c"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
