name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.122+mc21.11.fabric.vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ae751f0e35abb958e95c46c629d9d83c91d78d0241ee487e80d04fb89e9206d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
