name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f32a6d7a3d4b2c08c18087afcd23fd3d3ea6091e31de1df17b17b366a0ce2ca3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
