name = "Complexly Optimized"
author = "Ratchet"
version = "21.1.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c466a7b3940b00d6b6d6536d30389d04e0d5a9255516f1552480d860e6b8b940"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
