name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfb75d212cf3c7dc44ea0f063e7f250de14ceddae7a468e29d918ac46d2c95ec"

[versions]
fabric = "0.19.5"
minecraft = "1.21.4"
