name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.8-SNAPSHOT+mc21.1.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815e0c278d3ecf120c69a9f2ea56277af5469e45cffa415517de66647c5ba3bf"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
