name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.0+mc21.1.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeeb74f3fd707204ff62f9ade2238c3890d66d4ff4c428cb9ed1e646aedc76aa"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
