name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.15+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e50a93e95a96d0107c11ce1cb469cf3b9be7d0e018b4eaab7d72fa0c98bc31fb"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
