name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2954604daf2e80625a288a6667c8056cf4c0ac2234b6bb4bd02d7c302687df39"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
