name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6946e50a0f478224c7c3718415c6de0e5cca6facdf04da7d3016b0b202ca920"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
