name = "Complexly Optimized"
author = "Ratchet"
version = "12.2.1-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7765402e4b3b4f810cda5f66b5070f21d5cb7e75f32c0177314d8c9abfea35dd"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
