name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.117+mc21.1.neoforge.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6d06195c40a146aee3a1bbfa0365e21bb5e6f242139a1403146815d6e7fdb5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
