name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.15+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af203a52893c48a9e0bb6006bfbb8d8fc2ec10f36409719e7ad4efbb19a35ffc"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
