name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.27+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e040928fe3e40214b034095b9a20aed1af1065a5927ca2ed77a4010b4364022a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
