name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e0f83540af83bbdba7f20a17254f6e2a936516b1d200b2f946a40e0b9b3d536"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
