name = "Complexly Optimized"
author = "Ratchet"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37294f78a3372e23bb4dc4e9084c8f211b39d76ffac2a9da5f028b21ff6c1196"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
