name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-vanilla"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ece40bdade026849c029c493c7b4e87accabf5d6570cf808f262e3b4201dde16"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
