name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "384961775dab0f7a1abde8658e673232b9a0bea2e308dc942318294c61eacaa3"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
