name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31-SNAPSHOT+mc1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c8cb1fb8b6d9db1a0ff62b2d49ac523570ef530cad4b910c7c44593501c50f6"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
