name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4810c6766bb74d1a44d139e2df76ec409baccc2987ee0148f152d738aba73811"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
