name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcd9b89dffc7adbfe802ce68a74b61b78c925cb05e31fc25d78553bb8df81d94"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
