hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "configureddefaults/config/crash_assistant/config.toml"

[[files]]
file = "configureddefaults/config/cull-less-leaves.json"

[[files]]
file = "configureddefaults/config/dynamic_fps.json"

[[files]]
file = "configureddefaults/config/ferritecore.mixin.properties"

[[files]]
file = "configureddefaults/config/kerria.json"

[[files]]
file = "configureddefaults/config/modernfix-mixins.properties"

[[files]]
file = "configureddefaults/config/quick-pack.json"

[[files]]
file = "configureddefaults/options.txt"

[[files]]
file = "mods/asynclogger.pw.toml"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/flerovium.pw.toml"
metafile = true

[[files]]
file = "mods/gnetum.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/jasione.pw.toml"
metafile = true

[[files]]
file = "mods/kerria-opt.pw.toml"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/obe.pw.toml"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
metafile = true
