name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.30+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c39ef44290f05f8cf7f387cf205ad6c330114cb108d9adf002472d32516ff48"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
