name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5ac7ea6fef2699ed43ae306e2bf8c7792c896554f92091fdcd2ba00cc70751b"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
