name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44e25e241f6487af98cb1e6e550abda8f5255a98cbf4bbde4b805239867bf95f"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
