name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3878184f0835f7c8d13a97b44edeac330a817282a44dc9cae7c5573f471979f0"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
