name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a2940e4cb63bffae3873a5ea32d32209f7952b63195992466f126383d091ba5"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
