name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "822689b4ff6c85ce015c56263f099edd1cfa3df336a489a7d7f16beb30301d3e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
