name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.2+mc21.1.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faabfc02b07f3a91a1904fedcb0f2896145bd2d3b1a758b2b1c21e2c7f36c108"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
