name = "Complexly Optimized"
author = "Ratchet"
version = "18.2.1-fabric+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e4fe5df2543c917ed1887a894524f19a29adbfa1efd75ea75a63801cdefcf24"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
