name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36-SNAPSHOT+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "172e1d46b500ce9cc6d9e80e7cba5c5923614b198b4dca6f58bbbeca0871aac8"

[versions]
fabric = "0.19.5"
minecraft = "1.19.4"
