name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36-SNAPSHOT+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c643c917423d1ed80ac3ccc71afec89b8bb76f1e6cd7521c93f62816f8a91301"

[versions]
fabric = "0.19.5"
minecraft = "1.19.4"
