name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.9+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abccc4a0f0160e59c5c333f4dbf5b2e75cafe15c36cef9c2b2848cbbb69f8f6c"

[versions]
fabric = "0.19.5"
minecraft = "1.19.2"
