name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4c56c37830b2eb54dc5f6db51abd9666e18c99fa9244d0bb2651c644f81eb13"

[versions]
fabric = "0.19.5"
minecraft = "1.19.2"
