name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.14+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ef94f491884028b6033d0bcca39a965b86fcb5ce3d8030fa1fa9309c03c0c2"

[versions]
fabric = "0.19.5"
minecraft = "1.19.2"
