name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f1e7cb92686ca105472645fe8d54f8bf0b68cb27c0a8564bb85bcd92f34f687"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
