name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.30-SNAPSHOT+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e2a2b07ae2496a7a9c0f7ce5ef77c0803fb28f743051c9e1d0593085da167b4"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
