name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.37+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76302fd66e438ee14f7c9d2669d3655c51c2abd7054abd3658afccc61e2bd88c"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
