name = "Complexly Optimized"
author = "Ratchet"
version = "12.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe5da436edd96461d0d2ac572a560b9ecacbc655435e78665289b06c66589892"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
