name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-fabric-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2210f4aa66d97754c9b2623f9157f05fefb7f6e3cc4a00357c30833b5b544810"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
