name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-fabric-stable"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aad652275cd80a6ec654a9121e37bb4cbf5c99f569a9a26958e6a0bdb783a016"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
