name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.6-SNAPSHOT+mc26.1.neo.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e26a1bc1fb4707adcaa5e0812912d803632fc88e750b695f28999349b7ad552a"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"
