name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.6+mc26.1.neo.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b1ee88f63acad532635eff54861d398ff8b9596aa864e2e68921136e5bb4085"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"
