name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.7+mc26.1.neo.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8161fd7c3d3e1c405ff76d06ca5c06e6e6513faa8955fbf99784c08e7777b06"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"
