name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37781d245d85490ad94febfb46f0aade4d019f10fb31bb92c3e46672c2d893ff"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
