name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "765fff8e588317caf3c9f711bc5b5f421b1721c4a00cd4749c40ae3557c6f1ec"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
