name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-fabric-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58ff1be4a85d4e4cfcf7efe65aa572e95ae2c3a66dc0e49d080663fdd31b14e3"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
