name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1-fabric-normal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dddf9fa4f01915bedfb8c5f6bd9021b8d0d19ff662957979fbb6341f188ad9d0"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
