name = "Complexly Optimized"
author = "Ratchet"
version = ""
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f46a5fafa16de73eb786ddd77288ba60b9df62454761c4ff9e259281792964e0"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
