name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.3-SNAPSHOT+mc21.1.neo.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "894afd2b660737d2e50d00aa1f684d3762a97e19d445e07bfb409b0a5db4beff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
