name = "Complexly Optimized"
author = "Ratchet"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f85fdf892bc72e747dd141647a8a50f9fd782f7e56498587dcb55619cab6082"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
