hash-format = "sha256"

[[files]]
file = "config/FastQuit.cfg"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "config/forge_early.cfg"

[[files]]
file = "config/fpsreducer/fpsreducer.cfg"

[[files]]
file = "config/fugue.cfg"

[[files]]
file = "mods/alfheim-lighting-engine.pw.toml"
metafile = true

[[files]]
file = "mods/asynclogger.pw.toml"
metafile = true

[[files]]
file = "mods/chibi.pw.toml"
metafile = true

[[files]]
file = "mods/cleanroom-relauncher-unofficial.pw.toml"
metafile = true

[[files]]
file = "mods/configanytime.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/entity-culling.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
metafile = true

[[files]]
file = "mods/fugue.pw.toml"
metafile = true

[[files]]
file = "mods/gnetum.pw.toml"
metafile = true

[[files]]
file = "mods/mixin-booter.pw.toml"
metafile = true

[[files]]
file = "mods/naughthirium.pw.toml"
metafile = true

[[files]]
file = "mods/nothirium.pw.toml"
metafile = true

[[files]]
file = "mods/red-core.pw.toml"
metafile = true

[[files]]
file = "mods/renderlib.pw.toml"
metafile = true

[[files]]
file = "mods/stellarcore.pw.toml"
metafile = true

[[files]]
file = "mods/vintagefix.pw.toml"
metafile = true
