name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.37+mc1.12.2.cleanroom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac2e41f887842f34667a1388c7c0ac20e0f40f71a304ee9330861807e485da7"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
