name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.37+mc1.12.2.cleanroom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08eb46f1d80db4e6087e260d36071adedc3e8dcb59a3d17d9e6a4daa1ba6309f"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
