name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.39+mc1.12.2.cleanroom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
no-internal-hashes = true
