name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ec837ba4a08f679d10092f09c15fe467018fb0caabb356e0a302be0c52252f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
