name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de39291f4c203c43133875f3fa701c76763584e65631135576a6f7ea80fdf661"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
