name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.6+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce182b0da2ad3fe22a6011ab59e3b297047efb6feed7d607542a80c991ad9cad"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
