name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.12+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "433dc31b83a9e70b8bac6dcb33ce4c8b9bf1ef5fe5fd5e30253871eb1b29d66e"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
