name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.6+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae2f71882ca96d5167037902e8c03e03a6e9bf90b3118c7c56bd8a470c0a3a3"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
