name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.13+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47e4c1c2540031f58f0fa0b0a181cb983e6d53cca9054840370927027126c890"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
