name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.13-SNAPSHOT+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89a142fe1c8e503a33b7de71bd77c825d96371b62341ada3f8c95b19020f1089"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
