name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b579784ed3e0f17f735eba7e656c656ce5f90d85848329062e8c66887a679eb"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
