name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b74528d11f7eb5bb2bd6a85b351e6ba25c9bf2b44d07ddbaae2b37281ab7286c"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
