name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-memory"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0f26b55e7df94126b8e1e49e493f924e6290365a49ddf01c2f5f9ac405a29b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
