name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.18+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9fe02f8f9ee8cf419687721b62f4b41a0343467c09c595bcf7ee37a49cac0e3"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
