name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31-SNAPSHOT+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9be1b7f3f50c8e946e6a87423dc1372bf87e2e31408e60e8ac66154c556c8191"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
