name = "Complexly Optimized"
author = "Ratchet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e80a6ecfe125ab302b5508a13ed45b36eae4fdc4ea83bd9da2b40fafc2b9074"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
