name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0dc30acc9431c8d0c3a02839db962a69e33682e8c2f1643ad07997ce9b79012"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
