name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12390340d6d9b7965fb9146f39f7591a910feba4aaa7f1c760eb9d2c46ec62f3"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
