name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2a86b09b28daa7fdc91e2930f9c9baff040e04ef37f66e98c53b09bdf4f3cd2"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
