hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "config/dynamic_fps.json"

[[files]]
file = "config/embeddium-options.json"

[[files]]
file = "config/fastquit.toml"

[[files]]
file = "config/ferritecore.mixin.properties"

[[files]]
file = "config/kerria.json"

[[files]]
file = "config/modernfix-mixins.properties"

[[files]]
file = "mods/asynclogger.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/kerria.pw.toml"
metafile = true

[[files]]
file = "mods/krypton-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/radon.pw.toml"
metafile = true

[[files]]
file = "mods/roadrunner.pw.toml"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
metafile = true

[[files]]
file = "mods/textrues-embeddium-options.pw.toml"
metafile = true
