name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4098006bf3f7854477db47050ba715a2d4026f6fc498ea6e66d23005d33f7926"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
