name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.16+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba9b467ccedff9478216b4f551d5c695861c49b17d4e10df8502ec554c7557a2"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
