name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31-SNAPSHOT+mc1.16.5.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dce25e137a8aead6467346a1471f53271ad36f92618dd5abd66b4455d60ab8f"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
