name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d463827ee7ead06587da2e89b455964139e54620ac32e0ff96cd93ed33d6479"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
