name = "Complexly Optimized"
author = "Ratchet"
version = "21.11.1+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d85076f5f5983dc567a02b4197e2cfbc5b7db96ce581d87d194e8abc0e717ca"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
