name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.122+mc12.2.forge.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eb38f79cbe84251e7f9d4c98055dcd6c094c88f4650e007626417be95a6bb9a"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
