name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.38-SNAPSHOT+mc26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68ca5bd5ed36bc7f26e41e9112e8cf731398d51ae322580d9d025c48ab0e4a79"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
