name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.30-SNAPSHOT+mc26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9afdb3e0d2c47064b258f6acc1ac2df6ba36b4bf86248c4b354b1f6b2695769"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
