name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.29-SNAPSHOT+mc26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c1412eb00ccea0db08d3ad7135f4ce9bf3e8fd09baa783d4fa3ba2d013e415f"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
