name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.7-SNAPSHOT+mc21.11.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec93163e8c318ad903b5a62dba243101e94c738a428fef131dd6002729312b0a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
