name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.7+mc21.11.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a27c18c2a3c5e0dffa402dc929741542de028f2c550d269ae9f17d41aced0a8f"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
