name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.7-SNAPSHOT+mc21.11.fab.vkn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7af473b16c2ea816ecf2de282ecb54d7c306df18eff382e3ee6dfa63d386d677"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
