name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.10+mc1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e973148f8799bb1a4fdffe8aaafc7d656cf159bdd032101ab0a1ade59ba3378"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
