name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.9-SNAPSHOT+mc1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b78fd93b48bf569ce149734b92a741b2718ed2977fdca6fecc9b1b891f2e54"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
