name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bbe814960b0cb7077de6e8d27796e233c94f06924eff830d4ce0e53e804c768"

[versions]
fabric = "0.19.5"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
