name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769a53df00cb4b748f1af3607365ac14f7b7bad30863e505f6fc3e6fc5cdc653"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
