name = "Complexly Optimized"
author = "Ratchet"
version = "19.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33dc694668e0eba94e03d78d9a365ed3882a0b37c19ad1872c07cfa7ff6eb92e"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
