name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f5e3db50e2d4dd315ac0111e68020c7b3c80a1d14cbcd0f88ecafa136df7a9e"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
