name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "821a13cf966865b1f732000749f69370cd8b63dfced976e7367e1777c3ebdcc0"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
