name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "545e5d78be4fa9750580415e3509c92a2a852e9519028f2f9a585202203ddca4"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
