name = "Complexly Optimized"
author = "Ratchet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90a3c01e0b00bd551361cee9891a9b2214cb6c29fb773d8478cc029ca9ee49ff"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
