name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a166b3c3632f851acbfa00a095953dd322b95f99fef059d00088d5f7d51157f6"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
