name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adec28d7efcf2134fd56cfca324aa3db3ae4608f00dc2fd4d6030e05dddf7507"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
