name = "Complexly Optimized"
author = "Ratchet"
version = "12.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8026ac14cff02641f33135427ff4b4ed56d1c3fd663e009d1a02c4ffb445c350"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
