name = "Complexly Optimized"
author = "Ratchet"
version = "26.10.0+mc1.21.5.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.98"

[options]
no-internal-hashes = true
