name = "Complexly Optimized"
author = "Ratchet"
version = "26.10.1+mc1.21.8.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.54"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
no-internal-hashes = true
