name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418ca38f747fa7b109770698ebdbe11565ebeb1a3a1acc14a5061d44a63610ab"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
