name = "Complexly Optimized"
author = "Ratchet"
version = "26.1.2.1-fabric+vulkan"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e508ebd196288b8562c37dc103f9c6b677790af9c0fa99d6c91762778caab334"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
