name = "Complexly Optimized"
author = "Ratchet"
version = "26.10.1-SNAPSHOT+mc1.20.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.2"
neoforge = "20.2.93"

[options]
no-internal-hashes = true
