name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.23+mc26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4bd4a01d72f86a5a508e06dbbd0ab48df4f5b9e1425123ab57e9d6fb989e85b"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
