name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.36+mc26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9fb8a0da5196dfd498c70b3fea5b6dbe304384ad130a91219127fc2d2c7458a"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
