name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.31+mc26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aba08ba8be8fd0368d6b226ff78df39572136b0f787c112c929a5d90b7823e4"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
