name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.23+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b673af92d5211b94286457bbe1fa06e235d2714d18360b3788ca28bcfdd52cb"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
