name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.28-SNAPSHOT+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6c51f4e3aa5848ffd8841e5b14a4985d4b984f436e63d92495312579e13fc6b"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
