name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.17+mc1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3230899e60854c63911f6bb1b01574e6d8e7fb2af6a84413e240d6e9be85703e"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
