name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-forge-normal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c875582b66bcbc3cb7b5c2ce992bfbcc32bab56b0d350f350522d7dcaec1640"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
