name = "Complexly Optimized"
author = "Ratchet"
version = "16.5.1-forge-modded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ddd5f9b6325d8dab59a417464271b5f1efd1c4b23b8c3eabe3a384efe18f08d"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
