name = "Complexly Optimized"
author = "Ratchet"
version = "2026.08.122+mc16.5.fabric.anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b648ac708b00f985396cdf2804e883415078f1d30ee8b6f646654e611f9ff1b4"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
