name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-forge+anarchy"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b370f6df0243ae16049d0ff412d37279c22b30f72eb15cba0f64e5ae5691abcd"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
