name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.6+mc26.2.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3373ff876e067fb7f019c5fa408f4c2ffd6b9c67acf542a3d45e35be35b3275"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
