name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.2+mc26.2.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5853d9a03e38e9deaff0ee664c8db655fa99780b5b25f80006f5cadf55cd7c8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
