name = "Complexly Optimized"
author = "Ratchet"
version = "26.8.5+mc26.2.fab.ana"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8856aeb9afd20f601de3bfd9efa760f5861a202a156cdf4f2ba4ce104acde1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
