name: Prepare

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
        fabric_version:
          description: "Fabric version (e.g. 0.19.3)"
          required: false
          type: string
        
        quilt_version:
          description: "Quilt version (e.g. 0.30.1)"
          required: false
          type: string

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v7
      
      - name: Setup packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Update mods
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")
            (
              cd "$dir" || exit 1
              packwiz update -ay
            )
          done
      
      - name: Migrate loaders
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")

            IFS='/' read -ra parts <<< "${filepath#versions/}"
            loader="${parts[0]}"

            (
              cd "$dir" || exit 1
              case "$loader" in
                fabric)
                  if [ -n "${{ inputs.fabric_version }}" ]; then
                    packwiz migrate loader "${{ inputs.fabric_version }}"
                  fi
                  ;;
                quilt)
                  if [ -n "${{ inputs.quilt_version }}" ]; then
                    packwiz migrate loader "${{ inputs.quilt_version }}"
                  fi
                  ;;
                *)
                  packwiz migrate loader latest
                  ;;
              esac
            )
          done
      
      - name: Refresh packs
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")
            (
              cd "$dir" || exit 1
              packwiz refresh
            )
          done
      
      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update packs"
      
      - name: Find previous tag
        id: previous_tag
        run: |
          previous_tag=$(git tag --sort=-version:refname | head -n 1)
          if [ -z "$previous_tag" ]; then
            echo "No previous tag found" && exit 1
          fi
          echo "tag=$previous_tag" >> "$GITHUB_OUTPUT"

      - name: Create version
        id: version
        run: |
          year=$(date -u +'%y')
          month=$(date -u +'%-m')

          patch=$(git tag -l "${year}.${month}.*" | wc -l)
          version="${year}.${month}.${patch}-SNAPSHOT"

          echo "version=$version" >> "$GITHUB_OUTPUT"
      
      - name: Bump pack.toml version
        env:
          pack_version: ${{ steps.version.outputs.version }}
          previous_tag: ${{ steps.previous_tag.outputs.tag }}
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")
            if [ -n "$previous_tag" ] && git diff --quiet "$previous_tag" HEAD -- "$dir"; then
              continue
            fi

            IFS='/' read -ra parts <<< "${filepath#versions/}"
            loader="${parts[0]}"
            mc_version="${parts[1]}"

            full_version="${pack_version}+mc${mc_version}.${loader}"
            sed -i -E "s/^version = .*/version = \"${full_version}\"/" "$filepath"
          done

      - name: Commit snapshots
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: prepare ${{ steps.version.outputs.version }}"