name: Prepare

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
        fabric_version:
          description: "Fabric version (e.g. 0.19.3)"
          required: false
          type: string
        
        quilt_version:
          description: "Quilt version (e.g. 0.30.1)"
          required: false
          type: string

concurrency:
  group: packwiz-${{ github.ref }}
  cancel-in-progress: false
  queue: max

jobs:
  prepare:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          cache: false
      
      - name: Setup packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Update mods
        shell: bash
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")
            (
              cd "$dir"
              while true; do
                output=$(packwiz update -ay)
                echo "$output"

                if [[ "$output" != *'Failed to check updates for '* ]]; then
                  break
                fi

                echo "Update check failed! Retrying..."
                sleep 30
              done
            )
          done
      
      - name: Migrate loaders
        shell: bash
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")

            IFS='/' read -ra parts <<< "${filepath#versions/}"
            loader="${parts[0]}"

            (
              cd "$dir"
              case "$loader" in
                fabric)
                  version="${{ inputs.fabric_version }}"
                  ;;
                quilt)
                  version="${{ inputs.quilt_version }}"
                  ;;
                *)
                  version='latest'
                  ;;
              esac

              if [[ -z "$version" ]]; then
                exit 0
              fi

              until packwiz migrate loader "$version"; do
                echo 'Migration failed! Retrying...'
                sleep 10
              done
            )
          done
      
      - name: Commit snapshot
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update & prepare snapshot"
