name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      
      - name: Bump pack.toml version
        env:
          tag: ${{ github.ref_name }}
        run: |
          find versions -type f -name pack.toml | while IFS= read -rd pack; do
            relative="${pack#version/}"
            dir="$(dirname "$relative")"

            if [ "${#parts[@]}" -ne 4 ]; then
              exit 1
            fi

            IFS='/' read -ra parts <<< "$dir"

            mc_version="${parts[0]}"
            loader="${parts[1]}"
            flavor="${parts[2]}"

            full_version="${tag}+mc${mc_version}.${loader}.${flavor}"
            sed -iE \
            "s/^version[[:space:]]*=.*/version = \"$VERSION\"/" \
            "$PACK"
          done
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump versions"
      
      # Placed below to make commit changes faster (for impatient people like me)
      - name: Setup Go
        uses: actions/setup-go@v7
      
      - name: Setup packwiz
        run: go install github.com/packwiz/packwiz@latest
