name: Tag

on:
  workflow_dispatch:
    inputs:
        version:
          description: "Release version (e.g. 2026.01.0)"
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      
      - name: Check tag
        env:
          version: ${{ inputs.version }}
        run: |
          if git rev-parse "$version" >/dev/null 2>&1; then
            echo "Tag $version already exists."
            exit 1
          fi
      
      - name: Bump pack.toml version
        env:
          tag: ${{ github.ref_name }}
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            IFS='/' read -ra parts <<< "$filepath"
            mc_version="${parts[1]}"
            loader="${parts[2]}"
            flavor="${parts[3]}"

            full_version="${tag}+mc${mc_version}.${loader}.${flavor}"
            sed -i -E "s/^version\s*=\s*\".*\"/version = \"${full_version}\"/" "$filepath"
          done
      
      - name: Setup Go
        uses: actions/setup-go@v7
      
      - name: Setup packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Update mod versions
        run: |
          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
            dir=$(dirname "$filepath")
            (
              cd "$dir" || exit 1
              packwiz update -ay
            )
          done
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump versions"
      
      - name: Create tag
        env:
          version: ${{ inputs.version }}
        run: |
          git tag "$version"
          git push origin "$version"