name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.26+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "564942209d63aee903ae8adaeec7662b1f14d3686f0019157c42999a27edd2f4"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
