name = "Complexly Optimized"
author = "Ratchet"
version = "26.9.34-SNAPSHOT+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b1b4a74e8efbd53a6ae4d6a8a9e0a42799b4bbd49888bbe1e08968d495f6255"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
