name = "Complexly Optimized"
author = "Ratchet"
version = "21.5.1+lawful"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6cea82bc114db25ee34e6e6d7c1ce8416e6c0a95f403f7ba27715319f6226ba"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
