name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-aggressive"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90d2b86bd24e5c0e728c7a8d4c24d22ef7a850759384a62f36f01e8f589a7d6e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
