name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-aggressive"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda65b214dffe664b8c489f1630690c34ff5c7084ef3ac30626000276a550591"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
