name = "Complexly Optimized"
author = "Ratchet"
version = "26.2.0.1-aggressive"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43e7adec34d62c6529c4a4be2d5663045aa6fd5bb1d67bfb3f8d89f5347b107d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
