name = "Complexly Optimized"
author = "Ratchet"
version = "20.1.1-fabric-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d345fe9ea69a7cfef24c904ac86beb9443e64b9c036ba9772f52ff01ccb119b"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
